name: splitpath
version: '1.0'
synopsis: Safely split paths in many ways
description: A tool for splitting paths that's more reliable and straightforward than the usual combination of `basename` and bash built-ins like `##*.` and `%.*`. This tool has smarter support for extensions and spaces as well.
license: ISC
author: Dino Morelli
maintainer: dino@ui3.info
copyright: 2019 Dino Morelli
category: Application, Console, Scripting
extra-source-files:
- changelog.md
- .gitignore
- package.yaml
- README.md
- stack.yaml
- util/resources/appimage/splitpath*

github: dino-/splitpath

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

executables:
  splitpath:
    source-dirs: src/app
    main: Main.hs
    dependencies:
    - base >=4.10 && < 5
    - docopt
    - filepath
